fix: publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -13,8 +13,18 @@ jobs:
         uses: actions/setup-java@v4
         with:
           distribution: corretto
-          cache: gradle
           java-version: 21
+
+      - name: Cache Gradle
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper/
+          key: ${{ runner.os }}-gradle
+          restore-keys: |
+            ${{ runner.os }}-gradle
+
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v3
         with:
@@ -31,12 +41,36 @@ jobs:
           path: |
             ./versions/**/build/libs/*.jar
 
+  set-matrix:
+    runs-on: ubuntu-latest
+    outputs:
+      game_versions: ${{ steps.set-matrix.outputs.game_versions }}
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - id: set-matrix
+        run: |
+          BRANCH="${{ github.event.release.target_commitish }}"
+          if [ -f .github/targets.json ]; then
+            if jq -e --arg branch "$BRANCH" 'has($branch)' .github/targets.json > /dev/null; then
+              matrix=$(jq -c --arg branch "$BRANCH" '.[$branch]' .github/targets.json)
+              echo "game_versions=$matrix" >> $GITHUB_OUTPUT
+            else
+              echo "::error ::Branch '$BRANCH' is not supported for distribution!"
+              exit 1
+            fi
+          else
+            echo "::error ::.github/targets.json is missing!"
+            exit 1
+          fi
+
   distribute:
-    needs: build
-    runs-on: "ubuntu-latest"
+    needs: [ build, set-matrix ]
+    runs-on: ubuntu-latest
     strategy:
       matrix:
-        game_version: [ "1.21.6" ]
+        game_version: ${{ fromJson(needs.set-matrix.outputs.game_versions) }}
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -45,6 +79,16 @@ jobs:
         with:
           name: built-jars
           path: ./versions
+
+      - name: Determine Version Type
+        id: versioning
+        run: |
+          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
+            echo "type=beta" >> $GITHUB_OUTPUT
+          else
+            echo "type=release" >> $GITHUB_OUTPUT
+          fi
+
       - name: Publish to Modrinth, CurseForge, etc.
         uses: Kir-Antipov/mc-publish@v3.3
         with:
@@ -52,6 +96,7 @@ jobs:
             versions/${{ matrix.game_version }}/build/libs/!(*-@(dev|sources|javadoc)).jar
             versions/${{ matrix.game_version }}/build/libs/*-@(dev|sources|javadoc).jar
           version: ${{ github.ref_name }}+${{ matrix.game_version }}
+          version-type: ${{ steps.versioning.outputs.type }}
           modrinth-id: ${{ vars.MODRINTH_ID }}
           modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
           curseforge-id: ${{ vars.CURSEFORGE_ID }}
